# SPDX-License-Identifier: AGPL-3.0-only
# (c) 2026 Vahini Technologies.
#
# build_bundle.py — reproduce analyser/scripts/core/engine.bundle.js from src/.
#
# The browser only loads the packed bundle; the readable engine sources live in
# analyser/src/. This script concatenates the sources in the documented order
# (docs/BUILD.md), base64-encodes the UTF-8 bytes, and wraps them in the same
# self-decoding loader the existing bundle uses:
#
#     (0, eval)(decodeURIComponent(escape(atob(_v))));
#
# which is the inverse of  btoa(unescape(encodeURIComponent(src))), i.e. the
# base64 of the UTF-8 encoding of the concatenated source. Run after editing any
# file under analyser/src/:
#
#     python analyser/build_bundle.py
#
# Then open  analyser/Vahini Analyser.html?demo=report  and confirm a report
# renders with no console errors.

import base64
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# Order matters: app.js references globals defined by earlier modules.
SOURCES = [
    "src/engine/engine.js",
    "src/engine/factors.js",
    "src/engine/ocr.js",
    "src/engine/imu.js",
    "src/engine/forecast.js",
    "src/engine/craft.js",
    "src/engine/crops.js",
    "src/engine/letters.js",
    "src/engine/narrate.js",
    "src/report/report-render.js",
    "src/app/app.js",
    "src/app/share.js",
]

OUT = os.path.join(HERE, "scripts", "core", "engine.bundle.js")


def build():
    parts = []
    for rel in SOURCES:
        path = os.path.join(HERE, *rel.split("/"))
        with open(path, "r", encoding="utf-8") as f:
            parts.append(f.read())
    # A newline between files prevents a trailing // comment in one file from
    # swallowing the first line of the next.
    combined = "\n;\n".join(parts)
    b64 = base64.b64encode(combined.encode("utf-8")).decode("ascii")
    loader = (
        "/* Vahini engine - packed build. Generated by build_bundle.py — do not edit by hand. */\n"
        "(function(){ try {\n"
        f'  var _v = "{b64}";\n'
        "  (0, eval)(decodeURIComponent(escape(atob(_v))));\n"
        '} catch (e) { console.error("engine load failed", e); } })();\n'
    )
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(loader)
    return len(combined), len(b64)


if __name__ == "__main__":
    src_len, b64_len = build()
    print(f"[build] packed {len(SOURCES)} sources: {src_len} src chars -> {b64_len} base64 chars")
    print(f"[build] wrote {OUT}")
